title: Southwest nudibranchs
author: Matthias Liffers
email: m@tthi.as
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

social:
  twitter: mpfl
  facebook: 
  instagram: mpflx
  github: mpfl
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
